layerrule = animation slide, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-notification-window
layerrule = blur, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = animation slide right, swaync-control-center
layerrule = blur, swaync-control-center
layerrule = animation slide up, rofi
layerrule = ignorealpha 0.5, rofi
layerrule = dimaround, rofi
layerrule = blur, rofi
layerrule = animation slide down, waybar
layerrule = blur, waybar
layerrule = animation fade, selection

# layerrule = noanim, hyprpicker

animations {
    enabled = yes, please :)

    bezier = linear, 0, 0, 1, 1
    bezier = easeInCustom, 0.5, 0, 0.7, 0
    bezier = easeOutCustom, 0.3, 1, 0.5, 1
    bezier = easeOutBackCustom, 0.2, 1.2, 0.6, 1
    bezier = easeInBackCustom, 0.4, -0.11, 0.8, 0
    bezier = windowsInCustom, 0.2, 1.27, 0.6, 1

    # i dont normally use this one, but its fun :3
    bezier = bounce, 0.80, 1.40, 0, 0.88

    animation = global, 1, 4, easeOutCustom
    
    animation = windows, 1, 5, easeOutCustom
        animation = windowsIn, 1, 5, windowsInCustom, popin 40%
        animation = windowsOut, 1, 5, easeInBackCustom, popin 40%
	
    animation = layersIn, 1, 4, easeOutCustom, fade
    animation = layersOut, 1, 3, easeInCustom, fade
        animation = fadeLayersIn, 1, 3.5, easeOutCustom 
        animation = fadeLayersOut, 1, 3.5, easeOutCustom 
    
    animation = border, 1, 4, easeOutCustom

    animation = fade, 1, 3, easeOutCustom 
        animation = fadeIn, 1, 3, easeOutCustom
        animation = fadeOut, 1, 3, easeInCustom
     
    animation = workspaces, 1, 5.5, easeOutCustom, slide
        animation = specialWorkspace, 1, 5, easeOutCustom, slidevert
        animation = specialWorkspaceOut, 1, 3, easeInCustom, slidevert
}
