general {
    gaps_in = 7 
    gaps_out = 15 

    border_size = 6 

    col.active_border = rgba(FDBDFFFF) rgba(9DADFFFF) 90deg
    col.inactive_border = rgba(9D6D9FEE) rgba(3D5D96EE) 90deg
}

decoration {
    rounding = 16
	rounding_power = 4.0
	active_opacity = 0.9
    inactive_opacity = 0.8 
    
    dim_inactive = true
    dim_strength = 0.2

    shadow {
        enabled = true
        range = 5 
        render_power = 1 
        color = rgba(1A1A1ABB)
        offset = 5, 5
        scale = 1
    }

    blur {
        enabled = true
        xray = true 
        size = 3 
        passes = 5
        popups = true
        new_optimizations = true 
    }
}
