bindl = , switch:on:Lid Switch, exec, hyprlock --immediate

cursor {
    enable_hyprcursor = true 
    no_hardware_cursors = 1 
    use_cpu_buffer = 2 

    no_break_fs_vrr = 1
    min_refresh_rate = 60
    no_warps = false
    inactive_timeout = 2 
    default_monitor = DP-1
}

general {
    allow_tearing = true
    layout = dwindle
    resize_on_border = false
}

dwindle {
    pseudotile = true
    preserve_split = true
    split_bias = 2
}

master {
    new_status = slave
    mfact = 0.5
}

render {
    expand_undersized_textures = false 
    direct_scanout = 1 
}

misc {
    animate_manual_resizes = false 
    disable_autoreload = false 
    disable_hyprland_logo = true
    disable_hyprland_qtutils_check = true
    disable_splash_rendering = true
    focus_on_activate = false
    new_window_takes_over_fullscreen = 2
    vfr = 1 
    vrr = 1
    font_family = UbuntuMono Nerd Font 
}

debug {
    disable_logs = true
}
