$primary = DP-1
$secondary = HDMI-A-1

workspace = 1, monitor:$primary
workspace = 2, monitor:$primary
workspace = 3, monitor:$primary 
workspace = 4, monitor:$primary 
workspace = 5, monitor:$primary 
workspace = 6, monitor:$secondary
workspace = 7, monitor:$secondary
workspace = 8, monitor:$secondary
workspace = 9, monitor:$secondary
workspace = 10, monitor:$secondary

monitor = eDP-1, 1920x1080@60, 0x0, 1

monitor = $primary, 1920x1080@144, 0x0, 1, vrr, 2 
monitor = $secondary, 1920x1080@75, 1920x0, 1, vrr, 0
