plugin {
    hyprbars {
        bar_height = 30
        bar_color = rgba(FDBDFFFF)
        col.text = rgba(000000FF)
        bar_padding = 12
        bar_text_size = 14
        bar_text_font = UbuntuMono Nerd Font
        bar_text_align = left
        bar_part_of_window = true

        hyprbars-button = rgba(ff404000), 0
        hyprbars-button = rgba(eeee1100), 0
    }
}
