plugin {
    hyprbars {
        bar_height = 30
        bar_color = rgba(FDBDFFFF)
        bar_blur = true

        col.text = rgba(000000FF)
        bar_padding = 14
        bar_text_size = 16
        bar_text_font = UbuntuMono Nerd Font
        bar_text_align = center
        bar_part_of_window = true
        bar_precedence_over_border = true
        
        hyprbars-button = rgba(00000000), 0
        hyprbars-button = rgba(00000000), 0  
    }

    dynamic-cursors {
        enabled = true
        mode = stretch
        stretch {
            limit = 4000
            function = negative_quadratic
        }
        shake {
            nearest = false
            threshold = 8
            timeout = 1000
        }
    }
}

windowrulev2 = plugin:hyprbars:bar_color rgba(FDBDFFFF),focus:1
windowrulev2 = plugin:hyprbars:bar_color rgba(9D6D9FEE),focus:0

windowrulev2 = plugin:hyprbars:title_color rgba(000000FF),focus:1
windowrulev2 = plugin:hyprbars:title_color rgba(111111FF),focus:0
