#smart gaps
#workspace = w[tv1], gapsout:0, gapsin:0
#workspace = f[1], gapsout:0, gapsin:0
#windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
#windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
#windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
#windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

# tearing
windowrulev2 = immediate 1,class:^(osu!.exe)$
windowrulev2 = immediate 1,class:^(cs2)$

windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrulev2 = plugin:hyprbars:nobar,floating:1

windowrulev2 = workspace 1,class:^(firefox.*|zen)$
windowrulev2 = workspace 2,class:^(vesktop)$
windowrulev2 = workspace 2,class:^(.*)([Cc]ord)$
windowrulev2 = workspace 3,class:^(steam)$,title:^(Steam)$
windowrulev2 = workspace 4,class:^(foot)$
windowrulev2 = workspace 9,class:^(Spotify|spotify)$
windowrulev2 = workspace 10,class:^(com.obsproject.Studio)$
windowrulev2 = workspace 10,class:^(obs)$

# steam floats
windowrulev2 = size 500 700,class:^(steam)$,title:^(Friends List)$
windowrulev2 = center 1,class:^(steam)$,title:^(Friends List)$
windowrulev2 = float,class:^(steam)$,title:negative:^(Steam)$

# other

windowrulev2 = float,class:^(pcmanfm)$
windowrulev2 = float,class:^(eog)$
windowrulev2 = float,class:^(Bitwarden)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(love)$
windowrulev2 = float,class:^(firefox.*|zen)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(firefox.*|zen)$,title:^(Library)$
windowrulev2 = float,class:^(firefox.*|zen)$,title:^(Invalid Save Permissions)$
windowrulev2 = float,class:^(foot)$,title:^(btop)$
windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float,class:^(org.twosheds.iwgtk|iwgtk)$,title:^(.*)$

windowrulev2 = float,title:^(Open)$
windowrulev2 = float,title:^(Open File)$
windowrulev2 = float,title:^(Open Files)$
windowrulev2 = float,title:^(Choose Files)$
windowrulev2 = float,title:^(Save As)$
windowrulev2 = float,title:^(Confirm to replace files)$
windowrulev2 = float,title:^(File Operation Progress)$
windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$
