# tearing
windowrule = immediate,fullscreen:1

windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = plugin:hyprbars:nobar,floating:1
windowrule = bordersize 4,floating:1

windowrule = workspace 1,class:^(firefox.*|zen)$
windowrule = workspace 2,class:^(.*)([Cc]ord)$
windowrule = workspace 3,class:^(foot|footclient|Alacritty)$
windowrule = workspace 4,class:^(steam)$,title:^(Steam)$
windowrule = workspace 9,class:^(Spotify|spotify)$
windowrule = workspace 10,class:^(com.obsproject.Studio)$
windowrule = workspace 10,class:^(obs)$

windowrule = noinitialfocus,class:^(.*)([Cc]ord)$
windowrule = noinitialfocus,class:^(steam)$,title:^(Steam)$

# steam floats
windowrule = size 500 700,class:^(steam)$,title:^(Friends List)$
windowrule = center 1,class:^(steam)$,title:^(Friends List)$
windowrule = center 1,class:^()$,title:^(Steam)$
windowrule = float,class:^(steam)$,title:negative:^(Steam)$

# other

windowrule = float,class:^(piper)$
windowrule = float,class:^(nemo)$
windowrule = float,class:^(eog)$
windowrule = float,class:^(Bitwarden)$
windowrule = float,class:^(blueman-manager)$
windowrule = float,class:^(love)$
windowrule = float,class:^(firefox.*|zen)$,title:^(Picture-in-Picture)$
windowrule = float,class:^(firefox.*|zen)$,title:^(Library)$
windowrule = float,class:^(firefox.*|zen)$,title:^(Invalid Save Permissions)$
windowrule = float,class:^(foot)$,title:^(btop)$
windowrule = float,class:^(org.pulseaudio.pavucontrol)$
windowrule = float,class:^(org.twosheds.iwgtk|iwgtk)$,title:^(.*)$
windowrule = float,class:^(OpenTabletDriver.UX.Gtk)$
windowrule = float,class:^(io.missioncenter.MissionCenter)$

windowrule = float,title:^(Open)$
windowrule = float,title:^(Open File)$
windowrule = float,title:^(Open Files)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$
windowrule = float,class:^(xdg-desktop-portal-gtk)$
