# tearing
windowrule = immediate,fullscreen:1

windowrule = nodim,fullscreen:1
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = plugin:hyprbars:nobar,floating:1
windowrule = bordersize 4,floating:1

windowrule = workspace 1,class:^(firefox.*)$
windowrule = workspace 2,class:^(discord)$
windowrule = workspace 3,class:^(Alacritty)$
windowrule = workspace 4,class:^(steam)$,title:^(Steam)$
windowrule = workspace 10,class:^(com.obsproject.Studio)$
windowrule = workspace special:magic,class:^([Ss]potify)$

# no focus on open

windowrule = noinitialfocus,class:^(discord)$
windowrule = noinitialfocus,class:^(steam)$,title:^(Steam)$

# misc
windowrule = rounding 0,title:^(gsr ui)$
windowrule = noborder,title:^(gsr ui)$
windowrule = animation fade,title:^(gsr ui)$
windowrule = size 100% 100%,title:^(gsr ui)$

# steam thingies
windowrule = fullscreen,class:^(steam_app_.*)$
windowrule = size 500 700,class:^(steam)$,title:^(Friends List)$
windowrule = center 1,class:^(steam)$,title:^(Friends List)$
windowrule = center 1,class:^()$,title:^(Steam)$
windowrule = float,class:^(steam)$,title:negative:^(Steam)$

# other floats

windowrule = float,class:^(piper)$
windowrule = float,class:^(nemo)$
windowrule = float,class:^(eog)$
windowrule = float,class:^(Bitwarden)$
windowrule = float,class:^(blueman-manager)$
windowrule = float,class:^(love)$
windowrule = float,class:^(firefox.*|zen)$,title:^(Picture-in-Picture)$
windowrule = float,class:^(firefox.*|zen)$,title:^(Library)$
windowrule = float,class:^(firefox.*|zen)$,title:^(Invalid Save Permissions)$
windowrule = float,class:^(foot)$,title:^(btop)$
windowrule = float,class:^(org.pulseaudio.pavucontrol)$
windowrule = float,class:^(org.twosheds.iwgtk|iwgtk)$,title:^(.*)$
windowrule = float,class:^(OpenTabletDriver.UX.Gtk)$
windowrule = float,class:^(io.missioncenter.MissionCenter)$

windowrule = float,title:^(Open)$
windowrule = float,title:^(Open File)$
windowrule = float,title:^(Open Files)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$
windowrule = float,class:^(xdg-desktop-portal-gtk)$
